[project]
name = "ptracker"
version = "0.1"
description = ""
requires-python = ">=3.10,<4.0"
dependencies = []

[build-system]
requires = ["setuptools>=75"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
exclude = ["tests*"]